version: '3.3'
services:
  frps:
    restart: always
    network_mode: host
    volumes:
      - './frpc.ini:/etc/frp/frpc.ini'
    container_name: frps
    image: snowdreamtech/frps
    ports:
      - "5400:5400"
      - "9527:9527"