// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: proto/api.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ApiInfo_GetApiInfo_FullMethodName = "/ApiInfo/GetApiInfo"
)

// ApiInfoClient is the client API for ApiInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiInfoClient interface {
	GetApiInfo(ctx context.Context, in *ApiInfoGetRequest, opts ...grpc.CallOption) (*ApiInfoGetReply, error)
}

type apiInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewApiInfoClient(cc grpc.ClientConnInterface) ApiInfoClient {
	return &apiInfoClient{cc}
}

func (c *apiInfoClient) GetApiInfo(ctx context.Context, in *ApiInfoGetRequest, opts ...grpc.CallOption) (*ApiInfoGetReply, error) {
	out := new(ApiInfoGetReply)
	err := c.cc.Invoke(ctx, ApiInfo_GetApiInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiInfoServer is the server API for ApiInfo service.
// All implementations must embed UnimplementedApiInfoServer
// for forward compatibility
type ApiInfoServer interface {
	GetApiInfo(context.Context, *ApiInfoGetRequest) (*ApiInfoGetReply, error)
	mustEmbedUnimplementedApiInfoServer()
}

// UnimplementedApiInfoServer must be embedded to have forward compatible implementations.
type UnimplementedApiInfoServer struct {
}

func (UnimplementedApiInfoServer) GetApiInfo(context.Context, *ApiInfoGetRequest) (*ApiInfoGetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApiInfo not implemented")
}
func (UnimplementedApiInfoServer) mustEmbedUnimplementedApiInfoServer() {}

// UnsafeApiInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiInfoServer will
// result in compilation errors.
type UnsafeApiInfoServer interface {
	mustEmbedUnimplementedApiInfoServer()
}

func RegisterApiInfoServer(s grpc.ServiceRegistrar, srv ApiInfoServer) {
	s.RegisterService(&ApiInfo_ServiceDesc, srv)
}

func _ApiInfo_GetApiInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiInfoGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiInfoServer).GetApiInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiInfo_GetApiInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiInfoServer).GetApiInfo(ctx, req.(*ApiInfoGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApiInfo_ServiceDesc is the grpc.ServiceDesc for ApiInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApiInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ApiInfo",
	HandlerType: (*ApiInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetApiInfo",
			Handler:    _ApiInfo_GetApiInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api.proto",
}
